# -*- coding: utf-8 -*-
"""
Rewrite the brief in the first person: Yassine presenting his own project,
not a coach telling him what to do.

  - "you / your" addressed to Yassine become "I / my" (English and Arabic)
  - coaching-only lines are removed or reworded ("memorise", "careful",
    "read twice" tags, "know these cold", "read it aloud twice", ...)
  - generic "you" addressed to a visitor (e.g. the 3D kernel's "Try the green
    one") and the committee's quoted questions are left as they are
  - the spoken script and the Q&A answers were already first person

Every replacement must match exactly once, or the script stops without writing.
Usage:  python rewrite_first_person.py
"""
import io
import re
import sys

PATH = "index.html"
src = io.open(PATH, encoding="utf-8").read()

# 1. the "memorise" / "careful" / "read twice" marker tags
src, n_pens = re.subn(r'\s*<span class="pen(?: grey)?">(?:<svg.*?</svg>)?\s*[^<]*</span>', "", src)

R = [
    # ---------------- hero
    ('''<span class="tag en"><i></i> Master's thesis · HITSZ · defence brief</span>''',
     '''<span class="tag en"><i></i> Master's thesis · HITSZ · Yassine Achouak</span>'''),
    ('''<span class="tag ar"><i></i> أطروحة ماجستير · HITSZ · ملخّص المناقشة</span>''',
     '''<span class="tag ar"><i></i> أطروحة ماجستير · HITSZ · ياسين أشواك</span>'''),
    ('''<p class="lead">Everything you need to understand your own project, explain it out loud, and answer the committee. Every number here came from running code — none of it is quoted from a paper.</p>''',
     '''<p class="lead">I'm Yassine Achouak, a master's student at HIT Shenzhen. This is my thesis project: the problem I'm working on, the methods I'm building, and what I've measured so far. Every number here came from running my own code — none of it is quoted from a paper.</p>'''),
    ('''<p class="lead">كل ما تحتاجه لفهم مشروعك، وشرحه شفويًا، والإجابة على أسئلة اللجنة. كل رقم هنا نتج عن تشغيل الكود فعليًا — ولا شيء منه منقول من بحث.</p>''',
     '''<p class="lead">أنا ياسين أشواك، طالب ماجستير في معهد هاربين للتكنولوجيا بشنتشن. هذا مشروع أطروحتي: المشكلة التي أعمل عليها، والطريقتان اللتان أبنيهما، وما قِستُه حتى الآن. كل رقم هنا نتج عن تشغيل الكود الخاص بي فعليًا — ولا شيء منه منقول من بحث.</p>'''),
    ('parameters in the model you adapt', 'parameters in the model I adapt'),
    ('معامل في النموذج الذي تكيّفه', 'معامل في النموذج الذي أُكيّفه'),
    ('of them you actually train', 'of them I actually train'),
    ('فقط هي ما تدرّبه فعليًا', 'فقط هي ما أدرّبه فعليًا'),

    # ---------------- 01
    ('<h2 class="en">The five sentences</h2>', '<h2 class="en">My project in five sentences</h2>'),
    ('<h2 class="ar">الجمل الخمس</h2>', '<h2 class="ar">مشروعي في خمس جمل</h2>'),
    ('<p class="en">If your mind goes blank in the defence, these five get you back on the rails.</p>',
     '<p class="en">If you only read one part of this page, read this one.</p>'),
    ('<p class="ar">إذا توقف ذهنك أثناء المناقشة، هذه الجمل الخمس تعيدك إلى المسار.</p>',
     '<p class="ar">إن لم تقرأ من هذه الصفحة إلا جزءًا واحدًا، فليكن هذا.</p>'),
    ('["s1","01 · The five sentences","01 · الجمل الخمس"]', '["s1","01 · In five sentences","01 · في خمس جمل"]'),

    # ---------------- 02
    ('<h4 class="en">A trap the committee may set</h4>', '''<h4 class="en">A comparison I don't make</h4>'''),
    ('<h4 class="ar">فخ قد تنصبه اللجنة</h4>', '<h4 class="ar">مقارنة لا أُجريها</h4>'),
    ('<p class="en">Do <b>not</b> say "CSI drops', '<p class="en">I do <b>not</b> say "CSI drops'),
    ('<p class="ar"><b>لا</b> تقل: «قيمة CSI', '<p class="ar"><b>لا</b> أقول: «قيمة CSI'),

    # ---------------- 03
    ('(where you must make it work). Your supervisor confirmed all four are in scope.',
     '(where I need to make it work). My supervisor confirmed all four are in scope.'),
    ('والبقية <b>أهداف</b>. وقد أكّد مشرفك أن', 'والبقية <b>أهداف</b> (حيث عليّ أن أجعله يعمل). وقد أكّد مشرفي أن'),
    ('You cannot rescale one onto the other — decode both to real physical units first.',
     '''One can't simply be rescaled onto the other, so I decode both to real physical units first.'''),
    ('لا يمكن إعادة تحجيم إحداهما لتوافق الأخرى — فُكّ ترميزهما إلى وحدات فيزيائية أولًا.',
     'لا يمكن إعادة تحجيم إحداهما لتوافق الأخرى، لذا أفكّ ترميزهما إلى وحدات فيزيائية أولًا.'),
    ('<b>Report lead time in minutes, never frames.</b>', '<b>So I report lead time in minutes, never frames.</b>'),
    ('<b>اذكر الزمن بالدقائق لا باللقطات.</b>', '<b>لذا أذكر الزمن بالدقائق لا باللقطات.</b>'),
    ('Its numbers are not directly comparable — say so before someone catches it.',
     'Its numbers are not directly comparable, and I say so up front.'),
    ('أرقامها ليست قابلة للمقارنة المباشرة — قل ذلك قبل أن يكتشفه أحد.',
     'أرقامها ليست قابلة للمقارنة المباشرة، وأقول ذلك منذ البداية.'),

    # ---------------- 04
    ('<h2 class="en">AlphaPre — the model you freeze</h2>', '<h2 class="en">AlphaPre — the model I freeze</h2>'),
    ('<h2 class="ar">AlphaPre — النموذج الذي تُجمّده</h2>', '<h2 class="ar">AlphaPre — النموذج الذي أُجمّده</h2>'),
    ('''AlphaPre is a nowcasting model from <b>your own laboratory</b> (CVPR 2025). You did not build it and you do not claim it — you download its trained weights, freeze them, and adapt them. Being clear about that separation is one of the fastest ways to sound competent.''',
     '''AlphaPre is a nowcasting model from <b>my own laboratory</b> (CVPR 2025). I didn't build it and I don't claim it — I download its trained weights, freeze them, and adapt them. I keep that separation clear everywhere in the project.'''),
    ('AlphaPre نموذج تنبؤ آني من <b>مختبرك أنت</b> (CVPR 2025). لم تبنِه ولا تدّعي ملكيته — أنت تُنزِّل أوزانه المدرَّبة، وتُجمِّدها، ثم تُكيّفها. والوضوح في هذا الفصل من أسرع الطرق لتبدو متمكنًا.',
     'AlphaPre نموذج تنبؤ آني من <b>مختبري</b> (CVPR 2025). لم أبنِه ولا أدّعي ملكيته — أنا أُنزِّل أوزانه المدرَّبة، وأُجمِّدها، ثم أُكيّفها. وأحرص على وضوح هذا الفصل في المشروع كله.'),
    ('Why that 0.02% is the whole reason your project exists', 'Why that 0.02% is the whole reason my project exists'),
    ('لماذا تُمثّل نسبة 0.02% سببَ وجود مشروعك كله', 'لماذا تُمثّل نسبة 0.02% سببَ وجود مشروعي كله'),
    ('The method you extend (S²FT)', 'The method I extend (S²FT)'),
    ('That is not something you read — you measured it on the checkpoint file.',
     'That is not something I read — I measured it on the checkpoint file.'),
    ('الطريقة التي تُوسّعها (S²FT)', 'الطريقة التي أُوسّعها (S²FT)'),
    ('وهذا ليس شيئًا قرأته — بل قِستَه على ملف الأوزان.', 'وهذا ليس شيئًا قرأتُه — بل قِستُه على ملف الأوزان.'),

    # ---------------- 05
    ('Normally you adjust <i>every</i> number in it.', 'Normally <i>every</i> number in it is adjusted.'),
    ('عادةً تُعدّل <i>كل</i> رقم فيه.', 'عادةً يُعدَّل <i>كل</i> رقم فيه.'),
    ('LORA r=4 — WHAT YOU ACTUALLY TRAIN', 'LORA r=4 — WHAT I ACTUALLY TRAIN'),
    ('Your results hint at exactly this.', 'My results hint at exactly this.'),
    ('ونتائجك تشير إلى هذا بالضبط.', 'ونتائجي تشير إلى هذا بالضبط.'),

    # ---------------- 06
    ('<h2 class="en">The one picture that carries your whole argument</h2>',
     '<h2 class="en">The one picture that carries my whole argument</h2>'),
    ('<h2 class="ar">الصورة الواحدة التي تحمل حجّتك كلها</h2>', '<h2 class="ar">الصورة الواحدة التي تحمل حجّتي كلها</h2>'),
    ('<p class="en">If you learn only one technical thing here, learn this. It is where your contribution stops being borrowed and starts being yours.</p>',
     '<p class="en">If there is one technical idea to take from this page, it is this one. It is where my contribution stops being borrowed and becomes my own.</p>'),
    ('<p class="ar">إن لم تتعلم هنا إلا شيئًا تقنيًا واحدًا، فليكن هذا. هنا يتوقف إسهامك عن كونه مُستعارًا ويصبح إسهامك أنت.</p>',
     '<p class="ar">إن كانت هناك فكرة تقنية واحدة تُؤخذ من هذه الصفحة، فهي هذه. هنا يتوقف إسهامي عن كونه مُستعارًا ويصبح إسهامي أنا.</p>'),
    ('<span class="who en">Say it out loud like this</span>', '<span class="who en">How I put it</span>'),
    ('<span class="who ar">قُلها شفويًا هكذا</span>', '<span class="who ar">كيف أشرحها</span>'),
    ('Where this insight came from — a good story to tell', 'Where this insight came from'),
    ('من أين جاءت هذه الفكرة — قصة تستحق أن تُروى', 'من أين جاءت هذه الفكرة'),
    ('warned you directly:', 'warned me directly:'),
    ('''He has never tried the method on convolutions, and there is <b>no public implementation</b>. You are not adapting someone's code; you are deriving the extension from the paper and from a property you measured.''',
     '''The method has never been tried on convolutions, and there is <b>no public implementation</b>. I am not adapting someone's code; I am deriving the extension from the paper and from a property I measured.'''),
    ('حذّرك «يو تشيهاو»', 'حذّرني «يو تشيهاو»'),
    ('وهو لم يجرّب الطريقة على الالتفافات قط، ولا يوجد <b>أي تنفيذ عام</b>. أنت لا تُكيّف كود أحد، بل تشتق التوسعة من الورقة ومن خاصية قِستَها بنفسك.',
     'ولم تُجرَّب الطريقة على الالتفافات قط، ولا يوجد <b>أي تنفيذ عام</b>. أنا لا أُكيّف كود أحد، بل أشتق التوسعة من الورقة ومن خاصية قِستُها بنفسي.'),
    ('<b>This is the shuffle your method is allowed to make.</b>', '<b>This is the shuffle my method is allowed to make.</b>'),
    ('<b>هذا هو الخلط المسموح لطريقتك.</b>', '<b>هذا هو الخلط المسموح لطريقتي.</b>'),
    ('<b>This is the shuffle your method must never make.</b>', '<b>This is the shuffle my method must never make.</b>'),
    ('<b>هذا هو الخلط الممنوع على طريقتك.</b>', '<b>هذا هو الخلط الممنوع على طريقتي.</b>'),

    # ---------------- 07
    ('<span class="en">Your contribution</span><span class="ar">إسهامك</span>',
     '<span class="en">My contribution</span><span class="ar">إسهامي</span>'),
    ('<h2 class="en">Your two methods</h2>', '<h2 class="en">My two methods</h2>'),
    ('<h2 class="ar">طريقتاك</h2>', '<h2 class="ar">طريقتاي</h2>'),
    ('["s7","07 · Your two methods","07 · طريقتاك"]', '["s7","07 · My two methods","07 · طريقتاي"]'),
    ('the dial is k — how many you keep', 'the dial is k — how many are kept'),
    ('The question your thesis actually answers', 'The question my thesis actually answers'),
    ('السؤال الذي تجيب عنه أطروحتك فعليًا', 'السؤال الذي تجيب عنه أطروحتي فعليًا'),
    ('''These are equations (3-1), (3-2), (3-6) and (3-7) of the proposal, and they are on the “Method in Equations” slide. You don't need to derive them. You need to say in one sentence what each one means.''',
     '''These are equations (3-1), (3-2), (3-6) and (3-7) of my proposal, and they are on the “Method in Equations” slide of my defence. Each one is explained in one sentence below.'''),
    ('هذه هي المعادلات (3-1) و(3-2) و(3-6) و(3-7) في المقترح، وهي نفسها في شريحة «الطريقة بالمعادلات». لا تحتاج إلى اشتقاقها، بل إلى أن تقول في جملة واحدة ماذا تعني كل واحدة منها.',
     'هذه هي المعادلات (3-1) و(3-2) و(3-6) و(3-7) في مقترحي، وهي نفسها في شريحة «الطريقة بالمعادلات» في عرضي. وتحت كل واحدة منها شرح في جملة واحدة.'),
    ('<p class="en"><b>Your extension.</b> Keep a few coefficients <i>c</i>, place them in a spectrum (<i>S</i>), transform back (ℱ<sup>−1</sup>), keep the real part, then undo',
     '<p class="en"><b>My extension.</b> I keep a few coefficients <i>c</i>, place them in a spectrum (<i>S</i>), transform back (ℱ<sup>−1</sup>), keep the real part, then undo'),
    ('<p class="ar"><b>توسعتك.</b> تحتفظ بعدد قليل من المعاملات <i>c</i>، وتضعها في طيف (<i>S</i>)، ثم تعكس التحويل (ℱ<sup>−1</sup>)، وتأخذ الجزء الحقيقي، ثم تُلغي',
     '<p class="ar"><b>توسعتي.</b> أحتفظ بعدد قليل من المعاملات <i>c</i>، وأضعها في طيف (<i>S</i>)، ثم أعكس التحويل (ℱ<sup>−1</sup>)، وآخذ الجزء الحقيقي، ثم أُلغي'),
    ('<h4 class="en">The one sentence to remember</h4>', '<h4 class="en">The point of the two cost equations</h4>'),
    ('<h4 class="ar">الجملة الواحدة التي تحفظها</h4>', '<h4 class="ar">مغزى معادلتَي الكلفة</h4>'),
    ('Yours is 9<i>k</i> for every 3 × 3 kernel', 'Mine is 9<i>k</i> for every 3 × 3 kernel'),
    ('أما كلفتك فهي 9<i>k</i>', 'أما كلفة طريقتي فهي 9<i>k</i>'),

    # ---------------- 08
    ('<span class="en">Defending novelty</span><span class="ar">الدفاع عن الابتكار</span>',
     '<span class="en">Novelty</span><span class="ar">الابتكار</span>'),
    ('You are not proposing a better general method.<br>You are designing it for <i>this</i> kind of model.',
     'I am not proposing a better general method.<br>I am designing it for <i>this</i> kind of model.'),
    ('أنت لا تقترح طريقة عامة أفضل.<br>أنت تُصمّمها من أجل <i>هذا</i>', 'أنا لا أقترح طريقة عامة أفضل.<br>أنا أُصمّمها من أجل <i>هذا</i>'),
    ('''This is your supervisor's own framing, and it answers the hardest question you will get. If someone says <i>"other people have already done efficient fine-tuning for convolutions"</i> — they have, and it does not touch you. Those are general recipes tested on photographs. You are not competing with them, because you are not offering a general recipe.''',
     '''This framing comes from my supervisor, and it answers the hardest question about the project. Other people <i>have</i> already done efficient fine-tuning for convolutions — but those are general recipes, tested on photographs. I am not competing with them, because I am not offering a general recipe.'''),
    ('هذه صياغة مشرفك نفسه، وهي الجواب على أصعب سؤال قد تواجهه. فإن قال أحدهم: «لقد سبق أن أنجز آخرون ضبطًا دقيقًا كفؤًا للالتفافات» — نعم فعلوا، وهذا لا يمسّك. تلك وصفات عامة اختُبرت على الصور. وأنت لا تنافسها، لأنك لا تقدّم وصفة عامة.',
     'هذه الصياغة من مشرفي، وهي تجيب عن أصعب سؤال يُطرح على المشروع. نعم، سبق أن أنجز آخرون ضبطًا دقيقًا كفؤًا للالتفافات — لكنها وصفات عامة اختُبرت على الصور. وأنا لا أنافسها، لأنني لا أقدّم وصفة عامة.'),
    ('<span class="who en">The exact sentence to have ready</span>', '<span class="who en">In one sentence</span>'),
    ('<span class="who ar">الجملة التي يجب أن تكون جاهزة</span>', '<span class="who ar">في جملة واحدة</span>'),
    ('<h4 class="en">A naming trap</h4>', '<h4 class="en">A note on the name</h4>'),
    ('<h4 class="ar">فخ في التسمية</h4>', '<h4 class="ar">ملاحظة حول الاسم</h4>'),
    ('Yours is the one about <b>sparse spectrum</b>, from your lab. The other is about structured sparsity, by an unrelated group. Say the full name once',
     'Mine is the one about <b>sparse spectrum</b>, from my lab. The other is about structured sparsity, by an unrelated group. I say the full name once'),
    ('ورقتك هي المتعلقة بـ<b>الطيف المتناثر</b>، من مختبرك. والأخرى تتناول التناثر المُهيكَل، من مجموعة لا صلة لها. اذكر الاسم الكامل',
     'ورقتي هي المتعلقة بـ<b>الطيف المتناثر</b>، من مختبري. والأخرى تتناول التناثر المُهيكَل، من مجموعة لا صلة لها. لذا أذكر الاسم الكامل'),

    # ---------------- 09
    ('<b>Everyone before you trained and tested', '<b>Everyone before me trained and tested'),
    ('<b>كل من سبقك درّب', '<b>كل من سبقني درّب'),
    ('<h3 class="en">What existed, and what you add</h3>', '<h3 class="en">What existed, and what I add</h3>'),
    ('<h3 class="ar">ما كان موجودًا، وما تضيفه أنت</h3>', '<h3 class="ar">ما كان موجودًا، وما أضيفه أنا</h3>'),
    ('<th>What you add</th>', '<th>What I add</th>'),
    ('<td>You <b>freeze it</b> and move it', '<td>I <b>freeze it</b> and move it'),
    ('<td>You use that protocol for', '<td>I use that protocol for'),
    ('<td>You extend it to <b>convolutional kernels</b>', '<td>I extend it to <b>convolutional kernels</b>'),
    ('<td>You design around', '<td>I design around'),
    ('<th>ما تضيفه أنت</th>', '<th>ما أضيفه أنا</th>'),
    ('<td>أنت <b>تُجمّده</b> وتنقله إلى دولة أخرى</td>', '<td>أنا <b>أُجمّده</b> وأنقله إلى دولة أخرى</td>'),
    ('<td>أنت تستخدم البروتوكول', '<td>أنا أستخدم البروتوكول'),
    ('<td>أنت تُوسّعها إلى', '<td>أنا أُوسّعها إلى'),
    ('<td>أنت تُصمّم حول', '<td>أنا أُصمّم حول'),
    ('<h3 class="en">The three things that are actually yours</h3>', '<h3 class="en">The three things that are actually mine</h3>'),
    ('<h3 class="ar">الأشياء الثلاثة التي هي حقًا لك</h3>', '<h3 class="ar">الأشياء الثلاثة التي هي حقًا لي</h3>'),
    ('<div class="no">Yours 01</div>', '<div class="no">Mine 01</div>'),
    ('<div class="no">Yours 02</div>', '<div class="no">Mine 02</div>'),
    ('<div class="no">Yours 03</div>', '<div class="no">Mine 03</div>'),
    ('In the literature you surveyed,', 'In the literature I surveyed,'),
    ('في الأدبيات التي مسحتَها،', 'في الأدبيات التي مسحتُها،'),
    ('Your hardest technical contribution.', 'My hardest technical contribution.'),
    ('The paper&#39;s second author confirmed he has never tried it on convolutions, and there is <b>no public implementation</b>. You derive it from the paper, not from code.',
     'The paper&#39;s second author confirmed to me that it has never been tried on convolutions, and there is <b>no public implementation</b>. I derive it from the paper, not from code.'),
    ('أصعب إسهاماتك التقنية.', 'أصعب إسهاماتي التقنية.'),
    ('وقد أكّد المؤلف الثاني للورقة أنه لم يجرّبها على الالتفافات قط', 'وقد أكّد لي المؤلف الثاني للورقة أنها لم تُجرَّب على الالتفافات قط'),
    ('أنت تشتقّها من الورقة لا من كود.', 'أنا أشتقّها من الورقة لا من كود.'),
    ('<h4 class="en">What is NOT new — say this before they do</h4>', '<h4 class="en">What is NOT new</h4>'),
    ('<h4 class="ar">ما ليس جديدًا — قله قبل أن يقولوه</h4>', '<h4 class="ar">ما ليس جديدًا</h4>'),
    ('<b>PEFT itself is not yours</b>', '<b>PEFT itself is not mine</b>'),
    ('Your Research Content One is a baseline', 'My Research Content One is a baseline'),
    ('AlphaPre&#39;s</b>, not yours. What is yours is using it', 'AlphaPre&#39;s</b>, not mine. What is mine is using it'),
    ('<b>PEFT نفسها ليست لك</b>', '<b>PEFT نفسها ليست لي</b>'),
    ('محتوى بحثك الأول خط أساس', 'محتوى بحثي الأول خط أساس'),
    ('</b> لا منك. ما هو لك هو استخدامه', '</b> لا مني. ما هو لي هو استخدامه'),
    ('<p class="en">Claiming any of those would get you caught. Volunteering them makes the real claims land harder.</p>',
     '''<p class="en">I don't claim any of those. Being clear about them is what makes the real claims credible.</p>'''),
    ('<p class="ar">ادّعاء أيٍّ منها سيوقعك. أما التطوّع بذكرها فيجعل ادّعاءاتك الحقيقية أوقع.</p>',
     '<p class="ar">لا أدّعي أيًّا منها. والوضوح بشأنها هو ما يمنح ادّعاءاتي الحقيقية مصداقيتها.</p>'),
    ('<span class="who en">The sentence for the defence</span>', '<span class="who en">The whole project in one paragraph</span>'),
    ('<span class="who ar">الجملة المخصّصة للمناقشة</span>', '<span class="who ar">المشروع كله في فقرة واحدة</span>'),

    # ---------------- 10
    ('<span class="en">Your evidence</span><span class="ar">دليلك</span>', '<span class="en">My evidence</span><span class="ar">دليلي</span>'),
    ('<h2 class="en">What you have already measured</h2>', '<h2 class="en">What I have already measured</h2>'),
    ('<h2 class="ar">ما قِستَه بالفعل</h2>', '<h2 class="ar">ما قِستُه بالفعل</h2>'),
    ('["s10","10 · What you measured","10 · ما قِستَه"]', '["s10","10 · What I measured","10 · ما قِستُه"]'),
    ('This is your proof that you have done something — <b>know these cold</b>.',
     'They are the evidence that the project already works end to end.'),
    ('وهذه هي البرهان على أنك أنجزت شيئًا — <b>احفظها جيدًا</b>.', 'وهي البرهان على أن المشروع يعمل بالفعل من البداية إلى النهاية.'),
    ('<p class="en">You downloaded the trained model and counted its numbers.', '<p class="en">I downloaded the trained model and counted its numbers.'),
    ('<p class="ar">نزّلت النموذج المدرَّب وأحصيت أرقامه.', '<p class="ar">نزّلتُ النموذج المدرَّب وأحصيتُ أرقامه.'),
    ('<h4 class="en">Told you where to spend</h4><h4 class="ar">دلّك على أين تُنفق</h4>',
     '<h4 class="en">Told me where to spend</h4><h4 class="ar">دلّني على أين أُنفق</h4>'),
    ('not the thing you care about.', 'not the thing I care about.'),
    ('لا ما يهمّك.', 'لا ما يهمّني.'),
    ('Crucially you also ran a <b>control on SEVIR itself</b>, which proves a low transfer score cannot be blamed on a broken data loader. Committees respect controls.',
     'Crucially I also ran a <b>control on SEVIR itself</b>, which shows a low transfer score cannot be blamed on a broken data loader.'),
    ('على رادار لم ترَه. والأهم أنك أجريت <b>ضابطًا على SEVIR نفسها</b>، وهذا يثبت أن ضعف نتيجة النقل لا يُفسَّر بخلل في محمّل البيانات. واللجان تحترم الضوابط.',
     'على رادار لم يرَه. والأهم أنني أجريتُ <b>ضابطًا على SEVIR نفسها</b>، وهذا يثبت أن ضعف نتيجة النقل لا يُفسَّر بخلل في محمّل البيانات.'),
    ('predicted in your proposal:', 'predicted in my proposal:'),
    ('هذا أثر التنظيم الذي تنبّأتَ به في مقترحك:', 'هذا أثر التنظيم الذي تنبّأتُ به في مقترحي:'),

    # ---------------- 11
    ('<h2 class="en">What your results do <i>not</i> prove</h2>', '<h2 class="en">What my results do <i>not</i> prove</h2>'),
    ('<h2 class="ar">ما <i>لا</i> تُثبته نتائجك</h2>', '<h2 class="ar">ما <i>لا</i> تُثبته نتائجي</h2>'),
    ('<p class="en">Raising these yourself, before anyone asks, is the strongest move available in a defence. It converts a potential attack into evidence that you understand your own work.</p>',
     '<p class="en">These are the limits of what I have shown so far. I would rather state them myself than leave them for someone else to find.</p>'),
    ('<p class="ar">أن تطرح هذه النقاط بنفسك قبل أن يسألك أحد هو أقوى تحرّك متاح في المناقشة. فهو يحوّل هجومًا محتملًا إلى دليل على أنك تفهم عملك.</p>',
     '<p class="ar">هذه حدود ما أثبتُّه حتى الآن. وأفضّل أن أذكرها بنفسي على أن أتركها لغيري ليكتشفها.</p>'),
    ('Never present it as a demonstrated win.', '''I don't present it as a demonstrated win.'''),
    ('لا تقدّمه كانتصار مُبرهَن.', 'ولا أقدّمه كانتصار مُبرهَن.'),
    ('Seed repeats are the obvious next step, and saying so first shows you know what rigour requires.',
     'Seed repeats are the obvious next step, and they are first on my list.'),
    ('تكرار البذور هو الخطوة التالية البديهية، وذِكرُك لذلك أولًا يُظهر أنك تعرف ما تتطلبه الدقة العلمية.',
     'تكرار البذور هو الخطوة التالية البديهية، وهو أول ما في قائمتي.'),
    ('Say this plainly; it is a proposal, not a finished thesis.', 'I say this plainly: it is a proposal, not a finished thesis.'),
    ('قل هذا بوضوح؛ فهذا مقترح لا أطروحة مكتملة.', 'وأقول هذا بوضوح: هذا مقترح لا أطروحة مكتملة.'),

    # ---------------- 12
    ('<td>costs nothing. If it wins, you must say so.</td>', '<td>costs nothing. If it wins, I have to say so.</td>'),
    ('<td>لا تكلّف شيئًا. وإن تفوّقت وجب أن تقول ذلك.</td>', '<td>لا تكلّف شيئًا. وإن تفوّقت وجب أن أقول ذلك.</td>'),
    ('<h4 class="en">Arm 7 is the honest one — and it protects you</h4>', '<h4 class="en">Arm 7 is the honest one</h4>'),
    ('<h4 class="ar">الذراع السابعة هي الأمينة — وهي تحميك</h4>', '<h4 class="ar">الذراع السابعة هي الأمينة</h4>'),
    ('Your method has to beat it. <b>Including it is what makes the study credible</b>, and volunteering that makes you look rigorous rather than defensive.',
     'My method has to beat it. <b>Including it is what makes the study credible.</b>'),
    ('وعلى طريقتك أن تتفوّق عليها. <b>إدراجها هو ما يجعل الدراسة ذات مصداقية</b>، والتطوّع بذكرها يجعلك تبدو دقيقًا لا دفاعيًا.',
     'وعلى طريقتي أن تتفوّق عليها. <b>إدراجها هو ما يجعل الدراسة ذات مصداقية.</b>'),

    # ---------------- 13
    ('<h2 class="en">How to present, and how to sound like you know it</h2>', '<h2 class="en">How I am presenting it</h2>'),
    ('<h2 class="ar">كيف تعرض، وكيف تبدو متمكنًا</h2>', '<h2 class="ar">كيف أقدّم العرض</h2>'),
    ('["s13","13 · How to present","13 · كيف تعرض"]', '["s13","13 · How I present","13 · كيف أعرض"]'),
    ('Do <b>not</b> start with the literature. Start with the problem: a rain warning is only useful if it arrives in time, and these models do not cross borders. Then say what you do about it in one sentence. The room decides early whether you are confident.',
     'I do <b>not</b> start with the literature. I start with the problem: a rain warning is only useful if it arrives in time, and these models do not cross borders. Then I say what I do about it in one sentence.'),
    ('<b>لا</b> تبدأ بمراجعة الأدبيات. ابدأ بالمشكلة: التحذير من المطر لا يفيد إلا إذا وصل في وقته، وهذه النماذج لا تعبر الحدود. ثم قل ماذا تفعل حيال ذلك في جملة واحدة. القاعة تقرّر مبكرًا إن كنت واثقًا.',
     '<b>لا</b> أبدأ بمراجعة الأدبيات. أبدأ بالمشكلة: التحذير من المطر لا يفيد إلا إذا وصل في وقته، وهذه النماذج لا تعبر الحدود. ثم أقول ماذا أفعل حيال ذلك في جملة واحدة.'),
    ('Slow down here. Point at the four axes. Say which two may be shuffled and which two may not, and why. <b>If you rush this slide, the whole contribution sounds borrowed.</b>',
     '''I slow down here. I point at the four axes and say which two may be shuffled, which two may not, and why. <b>This slide is where the contribution becomes mine, so I don't rush it.</b>'''),
    ('تمهّل هنا. أشِر إلى المحاور الأربعة. قل أيّ محورين يجوز إعادة ترتيبهما وأيّهما لا، ولماذا. <b>إن تسرّعت في هذه الشريحة، بدا الإسهام كله مُستعارًا.</b>',
     'أتمهّل هنا. أشير إلى المحاور الأربعة وأقول أيّ محورين يجوز إعادة ترتيبهما وأيّهما لا، ولماذا. <b>في هذه الشريحة يصبح الإسهام إسهامي، لذا لا أتسرّع فيها.</b>'),
    ('Give the numbers out loud — 99.93%, 0.0805%, 1/1,242, 61.8% vs 33.8%. <b>Specific numbers are the fastest way to sound like someone who did the work</b>, because only someone who did it would know them.',
     'I give the numbers out loud — 99.93%, 0.0805%, 1/1,242, 61.8% vs 33.8%. <b>They are specific because I measured them.</b>'),
    ('انطق الأرقام بصوت مسموع — 99.93%، و0.0805%، و1/1,242، و61.8% مقابل 33.8%. <b>الأرقام المحددة أسرع طريقة لتبدو كمن أنجز العمل</b>، لأن من أنجزه وحده يعرفها.',
     'أنطق الأرقام بصوت مسموع — 99.93%، و0.0805%، و1/1,242، و61.8% مقابل 33.8%. <b>وهي محددة لأنني قِستُها بنفسي.</b>'),
    ('<h3 class="en">Six habits that make you sound like you understand it</h3>', '<h3 class="en">Six habits I keep while presenting</h3>'),
    ('<h3 class="ar">ست عادات تجعلك تبدو فاهمًا لعملك</h3>', '<h3 class="ar">ست عادات ألتزم بها أثناء العرض</h3>'),
    ('<li><b>Slow down deliberately.</b> Nervous people speed up, and speed reads as uncertainty. Say the first sentence of each slide slower than feels natural.</li>',
     '<li><b>I slow down deliberately.</b> Nerves make people speed up, and speed reads as uncertainty. I say the first sentence of each slide slower than feels natural.</li>'),
    ('<li><b>Never read the slide.</b> They can read. Say the thing the slide does <i>not</i> say — why it matters, or what it cost you to find out.</li>',
     '''<li><b>I don't read the slides.</b> The committee can read. I say what the slide does <i>not</i> say — why it matters, or what it took to find out.</li>'''),
    ('<li><b>Signpost constantly.</b> "There are two research contents. This is the first." "That was the method; now the experiments." It makes you sound in control of a structure — because you are.</li>',
     '<li><b>I signpost.</b> "There are two research contents. This is the first." "That was the method; now the experiments." It keeps the structure of the talk visible.</li>'),
    ('<li><b>Use exact numbers.</b>', '<li><b>I use exact numbers.</b>'),
    ('''<li><b>Say what is not yours.</b> "The frequency decomposition is AlphaPre's, not mine. What is mine is using it to decide where the budget goes." Nothing signals competence faster than cleanly separating your contribution from your inheritance.</li>''',
     '''<li><b>I say what is not mine.</b> "The frequency decomposition is AlphaPre's, not mine. What is mine is using it to decide where the budget goes." I keep my contribution cleanly separate from what I inherited.</li>'''),
    ('<li><b>Name the weakness first.</b> "AdaBN costs nothing and might beat me — that is why it is in the comparison." Raising it yourself removes its power as an attack.</li>',
     '<li><b>I name the weakness first.</b> "AdaBN costs nothing and might beat me — that is why it is in the comparison."</li>'),
    ('<li><b>تمهّل عمدًا.</b> المتوتّرون يُسرعون، والسرعة تُقرأ على أنها عدم يقين. انطق الجملة الأولى من كل شريحة أبطأ مما يبدو طبيعيًا.</li>',
     '<li><b>أتمهّل عمدًا.</b> التوتر يدفع إلى الإسراع، والسرعة تُقرأ على أنها عدم يقين. فأنطق الجملة الأولى من كل شريحة أبطأ مما يبدو طبيعيًا.</li>'),
    ('<li><b>لا تقرأ الشريحة أبدًا.</b> هم يستطيعون القراءة. قل ما <i>لا</i> تقوله الشريحة — لماذا يهمّ، أو ماذا كلّفك اكتشافه.</li>',
     '<li><b>لا أقرأ الشرائح.</b> فاللجنة تستطيع القراءة. أقول ما <i>لا</i> تقوله الشريحة — لماذا يهمّ، أو ماذا تطلّب اكتشافه.</li>'),
    ('<li><b>ضع لافتات إرشادية باستمرار.</b> «هناك محتويان بحثيان. هذا هو الأول.» «تلك كانت الطريقة؛ والآن التجارب.» هذا يجعلك تبدو مسيطرًا على بنية واضحة — لأنك كذلك فعلًا.</li>',
     '<li><b>أضع لافتات إرشادية.</b> «هناك محتويان بحثيان. هذا هو الأول.» «تلك كانت الطريقة؛ والآن التجارب.» هذا يُبقي بنية العرض واضحة.</li>'),
    ('<li><b>استخدم أرقامًا دقيقة.</b>', '<li><b>أستخدم أرقامًا دقيقة.</b>'),
    ('<li><b>قل ما ليس لك.</b> «التفكيك الترددي من AlphaPre وليس مني. ما هو لي هو استخدامه لتحديد أين تُنفَق الميزانية.» لا شيء يدل على الكفاءة أسرع من فصل إسهامك عن ميراثك بوضوح.</li>',
     '<li><b>أقول ما ليس لي.</b> «التفكيك الترددي من AlphaPre وليس مني. ما هو لي هو استخدامه لتحديد أين تُنفَق الميزانية.» وأُبقي إسهامي منفصلًا بوضوح عمّا ورثتُه.</li>'),
    ('<li><b>اذكر نقطة الضعف أولًا.</b> «AdaBN لا تكلّف شيئًا وقد تتفوّق عليّ — ولهذا أدرجتُها في المقارنة.» طرحُها بنفسك يجرّدها من قدرتها على أن تكون هجومًا.</li>',
     '<li><b>أذكر نقطة الضعف أولًا.</b> «AdaBN لا تكلّف شيئًا وقد تتفوّق عليّ — ولهذا أدرجتُها في المقارنة.»</li>'),
    ('<h4 class="en">The most common mistake — and one thing never to do</h4>', '<h4 class="en">Two things I avoid</h4>'),
    ('<h4 class="ar">أشيع خطأ — وأمر لا تفعله أبدًا</h4>', '<h4 class="ar">أمران أتجنّبهما</h4>'),
    ('''Spending eight minutes on related work because it feels safe, then rushing your own contribution because time is short. <b>The committee is not grading your summary of other people's papers.</b> Cut the literature to two minutes if you have to.''',
     '''Spending eight minutes on related work because it feels safe, then rushing my own contribution because time is short. <b>The committee is not grading a summary of other people's papers</b>, so I keep the literature to about two minutes.'''),
    ('أن تقضي ثماني دقائق في الأعمال ذات الصلة لأنها تبدو آمنة، ثم تتسرّع في إسهامك لأن الوقت ضاق. <b>اللجنة لا تقيّم تلخيصك لأوراق الآخرين.</b> اختصر الأدبيات إلى دقيقتين إن اضطررت.',
     'أن أقضي ثماني دقائق في الأعمال ذات الصلة لأنها تبدو آمنة، ثم أتسرّع في إسهامي لأن الوقت ضاق. <b>فاللجنة لا تقيّم تلخيصًا لأوراق الآخرين</b>، لذا أختصر الأدبيات إلى نحو دقيقتين.'),
    ('<b>And never apologise.</b> Not for your English, not for having partial results, not for anything. You are defending a plan backed by three real experiments — more than most people bring. Apologising invites them to agree that something is wrong.',
     '<b>And apologising.</b> Not for my English, not for having partial results. I am defending a plan backed by three real experiments, and there is nothing to apologise for.'),
    ('<b>ولا تعتذر أبدًا.</b> لا عن لغتك الإنجليزية، ولا عن كون نتائجك جزئية، ولا عن أي شيء. أنت تدافع عن خطة مدعومة بثلاث تجارب حقيقية — أكثر مما يحضره معظم الناس. والاعتذار يدعوهم للاتفاق على أن ثمة خطأ.',
     '<b>والاعتذار.</b> لا عن لغتي الإنجليزية، ولا عن كون نتائجي جزئية. فأنا أدافع عن خطة مدعومة بثلاث تجارب حقيقية، ولا شيء يستدعي الاعتذار.'),
    ('<h3 class="en">Handling questions — the four-step habit</h3>', '<h3 class="en">How I handle questions</h3>'),
    ('<h3 class="ar">التعامل مع الأسئلة — عادة من أربع خطوات</h3>', '<h3 class="ar">كيف أتعامل مع الأسئلة</h3>'),
    ('<h4 class="ar">توقّف</h4>', '<h4 class="ar">أتوقّف</h4>'),
    ('Two seconds. It looks considered, and it stops you answering the question you expected instead of the one you were asked.',
     'Two seconds. It stops me answering the question I expected instead of the one I was asked.'),
    ('ثانيتان. يبدو الأمر متأنيًا، ويمنعك من الإجابة على السؤال الذي توقّعته بدل الذي طُرح.',
     'ثانيتان. تمنعانني من الإجابة عن السؤال الذي توقّعتُه بدل الذي طُرح.'),
    ('<h4 class="ar">أعد الصياغة</h4>', '<h4 class="ar">أُعيد الصياغة</h4>'),
    ('Buys thinking time and confirms you understood.', 'It buys thinking time and confirms I understood.'),
    ('يمنحك وقتًا للتفكير ويؤكد أنك فهمت.', 'يمنحني وقتًا للتفكير ويؤكد أنني فهمت.'),
    ('Then stop. The short answer usually satisfies. If not they ask again — and now you know what they actually wanted.',
     'Then I stop. The short answer usually satisfies. If not, they ask again — and then I know what they actually wanted.'),
    ('ثم توقّف. الجواب القصير يكفي عادةً. وإن لم يكفِ سألوا مجددًا — وحينها تعرف ما أرادوه فعلًا.',
     'ثم أتوقّف. الجواب القصير يكفي عادةً. وإن لم يكفِ سألوا مجددًا — وحينها أعرف ما أرادوه فعلًا.'),
    ('<h4 class="ar">أشِر إلى الدليل</h4>', '<h4 class="ar">أشير إلى الدليل</h4>'),
    ('it is in the preliminary experiments." Show where it lives.', 'it is in the preliminary experiments." I show where it lives.'),
    ('«هذا مقيس — وهو في التجارب الأولية.» بيِّن أين يوجد.', '«هذا مقيس — وهو في التجارب الأولية.» وأُبيّن أين يوجد.'),
    ('<span class="who en">When you genuinely do not know</span>', '<span class="who en">When I genuinely do not know</span>'),
    ('<span class="who ar">حين لا تعرف الجواب فعلًا</span>', '<span class="who ar">حين لا أعرف الجواب فعلًا</span>'),
    ('<p class="en">This will happen, and it is survivable. <b>What is not survivable is inventing an answer.</b></p>',
     '<p class="en">This will happen, and that is fine. <b>What I never do is invent an answer.</b></p>'),
    ('<p class="ar">سيحدث هذا، ويمكن تجاوزه. <b>أما ما لا يمكن تجاوزه فهو اختلاق إجابة.</b></p>',
     '<p class="ar">سيحدث هذا، ولا بأس. <b>أما ما لا أفعله أبدًا فهو اختلاق إجابة.</b></p>'),
    ('<h4 class="en">The two questions you are most likely to get</h4>', '<h4 class="en">The two questions I am most likely to get</h4>'),
    ('<h4 class="ar">السؤالان الأرجح أن يُطرحا عليك</h4>', '<h4 class="ar">السؤالان الأرجح أن يُطرحا عليّ</h4>'),
    ('→ You are not proposing a general method, so you are not competing with them.',
     '→ I am not proposing a general method, so I am not competing with them.'),
    ('← أنت لا تقترح طريقة عامة، فلستَ منافسًا لها.', '← أنا لا أقترح طريقة عامة، فلستُ منافسًا لها.'),
    ('→ You measured the model before designing for it, and the measurement changed the design. Then give the three experiments and their numbers.',
     '→ I measured the model before designing for it, and the measurement changed the design. Then I give the three experiments and their numbers.'),
    ('← قِستَ النموذج قبل أن تُصمّم له، والقياس غيّر التصميم. ثم اذكر التجارب الثلاث وأرقامها.',
     '← قِستُ النموذج قبل أن أُصمّم له، والقياس غيّر التصميم. ثم أذكر التجارب الثلاث وأرقامها.'),

    # ---------------- 14
    ('<h2 class="en">The script — what to say</h2>', '<h2 class="en">My talk, slide by slide</h2>'),
    ('<h2 class="ar">النص — ما ينبغي أن تقوله</h2>', '<h2 class="ar">عرضي، شريحة بشريحة</h2>'),
    ('["s14","14 · The script","14 · النص"]', '["s14","14 · My talk","14 · عرضي"]'),
    ('This is exactly what is in the speaker notes of the deck, so you can learn it here and read it there. Numbers are written the way they should be said out loud.',
     'This is what I say over each slide of my defence. Numbers are written the way I say them out loud.'),
    ('هذا هو نصّ ملاحظات المتحدّث في العرض حرفيًا، فيمكنك حفظه هنا وقراءته هناك. والأرقام مكتوبة بالطريقة التي يجب أن تُنطق بها.',
     'هذا ما أقوله عند كل شريحة في عرض المناقشة. والأرقام مكتوبة بالطريقة التي أنطقها بها.'),
    ('  <p class="en">Read the whole thing aloud twice. The second time, look up at the end of every paragraph.</p>\n'
     '  <p class="ar">اقرأ النص كاملًا بصوت مسموع مرتين. وفي المرة الثانية، ارفع بصرك في نهاية كل فقرة.</p>\n', ''),
    ('<span class="mono" style="color:var(--mark)">NEW SLIDE</span>', '<span class="mono" style="color:var(--mark)">SLIDE 08B</span>'),

    # ---------------- 15
    ('<h2 class="en">Questions they will ask</h2>', '<h2 class="en">Questions I expect, and my answers</h2>'),
    ('<h2 class="ar">الأسئلة التي سيطرحونها</h2>', '<h2 class="ar">الأسئلة التي أتوقعها، وأجوبتي</h2>'),
    ('["s15","15 · Questions they will ask","15 · الأسئلة المتوقعة"]', '["s15","15 · Questions I expect","15 · الأسئلة المتوقعة"]'),
    ('Grouped by what the question is really testing. Read the answer, then say it in your own words — a memorised answer sounds memorised.',
     'Grouped by what each question is really testing, with the answer I give.'),
    ('مُجمَّعة حسب ما يختبره السؤال فعلًا. اقرأ الجواب ثم قله بكلماتك — فالجواب المحفوظ يبدو محفوظًا.',
     'مُجمَّعة حسب ما يختبره كل سؤال فعلًا، مع الجواب الذي أقدّمه.'),
    ('<h3 class="en">Your evidence</h3>', '<h3 class="en">My evidence</h3>'),
    ('<h3 class="ar">دليلك</h3>', '<h3 class="ar">دليلي</h3>'),
    ('<span class="who en">If you genuinely do not know</span>', '<span class="who en">If I genuinely do not know</span>'),
    ('<span class="who ar">إذا كنت لا تعرف فعلًا</span>', '<span class="who ar">إذا كنتُ لا أعرف فعلًا</span>'),
    ('This will happen at least once, and it is survivable.', 'This will happen at least once, and that is fine.'),

    # ---------------- 16
    ('<h2 class="en">The papers you are standing on</h2>', '<h2 class="en">The papers I am building on</h2>'),
    ('<h2 class="ar">الأوراق البحثية التي تقف عليها</h2>', '<h2 class="ar">الأوراق البحثية التي أبني عليها</h2>'),
    ('<p class="en">Three came out of your own laboratory, and your supervisor is an author on two. Worth knowing if someone asks why this project sits here.</p>',
     '<p class="en">Three came out of my own laboratory, and my supervisor is an author on two, which is why this project sits where it does.</p>'),
    ('<p class="ar">ثلاث منها خرجت من مختبرك، ومشرفك مؤلف في اثنتين. من المفيد معرفة ذلك إن سُئلت لماذا يقع هذا المشروع هنا.</p>',
     '<p class="ar">ثلاث منها خرجت من مختبري، ومشرفي مؤلف في اثنتين، ولهذا يقع هذا المشروع حيث يقع.</p>'),
    ('CVPR 2025 · YOUR LAB', 'CVPR 2025 · MY LAB'),
    ('CVPR 2026 · YOUR LAB', 'CVPR 2026 · MY LAB'),
    ('<b>This is the model you adapt</b> — its released weights are your starting point.',
     '<b>This is the model I adapt</b> — its released weights are my starting point.'),
    ('<b>هذا هو النموذج الذي تُكيّفه</b> — وأوزانه المنشورة هي نقطة انطلاقك.',
     '<b>هذا هو النموذج الذي أُكيّفه</b> — وأوزانه المنشورة هي نقطة انطلاقي.'),
    ('<b>This is the method you extend.</b> Your supervisor is first author. <b>No public code</b> — you write it from the paper.',
     '<b>This is the method I extend.</b> My supervisor is first author. <b>No public code</b> — I write it from the paper.'),
    ('<b>هذه هي الطريقة التي تُوسّعها.</b> ومشرفك مؤلفها الأول. <b>ولا يوجد كود عام</b> — أنت تكتبه من الورقة.',
     '<b>هذه هي الطريقة التي أُوسّعها.</b> ومشرفي مؤلفها الأول. <b>ولا يوجد كود عام</b> — أنا أكتبه من الورقة.'),
    ('so your implementation starts here', 'so my implementation starts here'),
    ('لذا يبدأ تنفيذك منها', 'لذا يبدأ تنفيذي منها'),
    ('Ancestor of your Research Content One, and one of your comparison arms', 'Ancestor of my Research Content One, and one of my comparison arms'),
    ('سلف محتوى بحثك الأول', 'سلف محتوى بحثي الأول'),
    ('the 5→20 at 128×128 protocol you adopt.', 'the 5→20 at 128×128 protocol I adopt.'),
    ('بدقة 128×128 الذي تتبنّاه.', 'بدقة 128×128 الذي أتبنّاه.'),

    # ---------------- 17
    ('<p class="en">Only the ones you will actually hear on the day.</p>', '<p class="en">Only the terms that actually come up in my defence.</p>'),
    ('<p class="ar">فقط الكلمات التي ستسمعها فعلًا يوم المناقشة.</p>', '<p class="ar">فقط المصطلحات التي ترد فعلًا في مناقشتي.</p>'),
    ('<dd>one of the numbers inside the model. Yours has 89 million</dd>', '<dd>one of the numbers inside the model. Mine has 89 million</dd>'),
    ('نموذجك يحوي 89 مليونًا', 'نموذجي يحوي 89 مليونًا'),
    ('<dd>a number you have decided not to change</dd>', '<dd>a number that is kept fixed during training</dd>'),
    ('<dd>مُجمَّد — رقم قرّرتَ ألّا تغيّره</dd>', '<dd>مُجمَّد — رقم يبقى ثابتًا أثناء التدريب</dd>'),
    ('so you store only a few</dd>', 'so only a few are stored</dd>'),
    ('فتخزّن القليل فقط</dd>', 'فيُخزَّن القليل فقط</dd>'),
    ('<dd>an alternative you compare against, to prove yours is worth it</dd>', '<dd>an alternative I compare against, to show mine is worth it</dd>'),
    ('<dd>خط الأساس — بديل تقارن به لتثبت أن طريقتك تستحق</dd>', '<dd>خط الأساس — بديل أقارن به لأُثبت أن طريقتي تستحق</dd>'),

    # ---------------- 18 + footer
    ("(supervisor's instruction)", "(my supervisor's request)"),
    ('(تعليمات المشرف)', '(بطلب من مشرفي)'),
    ('<span class="who en">The last thing to remember</span>', '<span class="who en">Where that leaves me</span>'),
    ('<span class="who ar">آخر ما ينبغي تذكّره</span>', '<span class="who ar">أين يضعني هذا</span>'),
    ('You are defending a <b>plan</b>, not a finished thesis. Nobody expects a complete result at this stage — and you arrive with <b>three real experiments</b>, which is more than most people bring. If you can draw the kernel and say why two axes may be shuffled and two may not, the technical core of your defence is safe.',
     'I am defending a <b>plan</b>, not a finished thesis. Nobody expects a complete result at this stage — and I arrive with <b>three real experiments</b> behind it. The technical core, why two axes of a kernel may be shuffled and two may not, is already worked out and backed by measurement.'),
    ('أنت تدافع عن <b>خطة</b>، لا عن أطروحة مكتملة. لا أحد يتوقع نتيجة نهائية في هذه المرحلة — وأنت تحضر بـ<b>ثلاث تجارب حقيقية</b>، وهذا أكثر مما يحضره معظم الناس. وإن استطعت رسم النواة وشرح لماذا يجوز إعادة ترتيب محورين ولا يجوز للآخرين، فإن الجوهر التقني لدفاعك في أمان.',
     'أنا أدافع عن <b>خطة</b>، لا عن أطروحة مكتملة. لا أحد يتوقع نتيجة نهائية في هذه المرحلة — وأنا أحضر ومعي <b>ثلاث تجارب حقيقية</b>. أما الجوهر التقني، أي لماذا يجوز إعادة ترتيب محورين من محاور النواة ولا يجوز للآخرين، فهو محسوم ومدعوم بالقياس.'),
    ('PRIVATE STUDY BRIEF · EVERY FIGURE', 'PROJECT BRIEF · YASSINE ACHOUAK · HITSZ · EVERY FIGURE'),
    ('ملخّص دراسي خاص ·', 'ملخّص المشروع · ياسين أشواك · HITSZ ·'),
]

bad = []
for old, new in R:
    c = src.count(old)
    if c != 1:
        bad.append((c, old[:90]))
        continue
    src = src.replace(old, new)

if bad:
    for c, o in bad:
        print("MATCHED %d TIMES: %s" % (c, o))
    sys.exit("not written: %d replacement(s) did not match exactly once" % len(bad))

# keep the file's own line endings (universal-newline read turned CRLF into \n)
crlf = b"\r\n" in io.open(PATH, "rb").read(4096)
io.open(PATH, "w", encoding="utf-8", newline="\r\n" if crlf else "\n").write(src)
print("marker tags removed: %d   replacements: %d   wrote %s" % (n_pens, len(R), PATH))
